package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-15T01:10:24.848-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://logistica.interfaces/", name = "IRecibirOrdenDespachoWs")
@XmlSeeAlso({ObjectFactory.class})
public interface IRecibirOrdenDespachoWs {

    @WebMethod(action = "urn:RecibirOrdenDespacho")
    @RequestWrapper(localName = "recibirOrdenDespacho", targetNamespace = "http://logistica.interfaces/", className = "wsclient.RecibirOrdenDespacho")
    @ResponseWrapper(localName = "recibirOrdenDespachoResponse", targetNamespace = "http://logistica.interfaces/", className = "wsclient.RecibirOrdenDespachoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public RespuestaGenerica recibirOrdenDespacho(
        @WebParam(name = "despacho", targetNamespace = "")
        OrdenDespacho despacho
    );
}
