package com.monitor.webservice;

import java.rmi.RemoteException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-02T19:49:03.497-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://webService.monitor.com/", name = "WSProcVentaBean")
@XmlSeeAlso({ObjectFactory.class})
public interface WSProcVentaBean {

    @WebMethod
    @RequestWrapper(localName = "procesarCarrito", targetNamespace = "http://webService.monitor.com/", className = "com.monitor.webservice.ProcesarCarrito")
    @ResponseWrapper(localName = "procesarCarritoResponse", targetNamespace = "http://webService.monitor.com/", className = "com.monitor.webservice.ProcesarCarritoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String procesarCarrito(
        @WebParam(name = "arg0", targetNamespace = "")
        com.monitor.webservice.VoCarrito arg0
    ) throws RemoteException;

    @WebMethod
    @RequestWrapper(localName = "procesarVenta", targetNamespace = "http://webService.monitor.com/", className = "com.monitor.webservice.ProcesarVenta")
    @ResponseWrapper(localName = "procesarVentaResponse", targetNamespace = "http://webService.monitor.com/", className = "com.monitor.webservice.ProcesarVentaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String procesarVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        com.monitor.webservice.VoVenta arg0
    ) throws RemoteException;
}
