package com.monitor.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-02T19:49:03.555-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "WSProcVentaBeanService", 
                  wsdlLocation = "file:/D:/Users/uade/git/TP_AI/TP_AIEAR/EarContent/resources/wsdl.wsdl",
                  targetNamespace = "http://webService.monitor.com/") 
public class WSProcVentaBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.monitor.com/", "WSProcVentaBeanService");
    public final static QName WSProcVentaBeanPort = new QName("http://webService.monitor.com/", "WSProcVentaBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Users/uade/git/TP_AI/TP_AIEAR/EarContent/resources/wsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSProcVentaBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Users/uade/git/TP_AI/TP_AIEAR/EarContent/resources/wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSProcVentaBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSProcVentaBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSProcVentaBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSProcVentaBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSProcVentaBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSProcVentaBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WSProcVentaBean
     */
    @WebEndpoint(name = "WSProcVentaBeanPort")
    public WSProcVentaBean getWSProcVentaBeanPort() {
        return super.getPort(WSProcVentaBeanPort, WSProcVentaBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSProcVentaBean
     */
    @WebEndpoint(name = "WSProcVentaBeanPort")
    public WSProcVentaBean getWSProcVentaBeanPort(WebServiceFeature... features) {
        return super.getPort(WSProcVentaBeanPort, WSProcVentaBean.class, features);
    }

}
