package interfaces.logistica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-11-15T21:16:44.351-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://logistica.interfaces/", name = "IRecibirOrdenDespachoWs")
@XmlSeeAlso({ObjectFactory.class})
public interface IRecibirOrdenDespachoWs {

    @WebMethod(action = "urn:RecibirOrdenDespacho")
    @RequestWrapper(localName = "recibirOrdenDespacho", targetNamespace = "http://logistica.interfaces/", className = "interfaces.logistica.RecibirOrdenDespacho")
    @ResponseWrapper(localName = "recibirOrdenDespachoResponse", targetNamespace = "http://logistica.interfaces/", className = "interfaces.logistica.RecibirOrdenDespachoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public interfaces.logistica.RespuestaGenerica recibirOrdenDespacho(
        @WebParam(name = "despacho", targetNamespace = "")
        interfaces.logistica.OrdenDespacho despacho
    );
}
